name: deployInternshalla
on:
  push:
    branches:
      - main
      - 'feat/**'
jobs:
  deploycode:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: print node
        run: | 
          echo "node is install successfully"
          node -v
      - name: create a cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{runner.os}}-build-${{hashFiles('**/package-lock.json')}}
      - name: Dependencies install
        run: |
          npm ci
          echo "dependencies install successfully"
      - name: Code deploy
        run: |
          npm run build
          echo "build successful"
  afterdeploy:
    needs: deploycode
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: print node
        run: |
          node -v
          echo "node install"
      - name: create a cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{runner.os}}-build-${{hashFiles('**/package-lock.json')}}
      - name: dependencies install
        run: | 
          npm ci
          echo "hello world"
