name: deployInternshalla
on:
  push:
    branches:
      - main
      - "feat/**"
    paths-ignore:
      - ".github/workflows/*"
      - "README.md"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: print node
        run: |
          echo "node is install successfully"
          node -v
      - name: create a cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{runner.os}}-build-${{hashFiles('**/package-lock.json')}}
      - name: Dependencies install
        run: |
          npm ci
          echo "dependencies install successfully"
      - name: Code deploy
        run: |
          npm run build
          echo "build successful"
      - name: Upload a artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: matrix
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages 
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        # with:
          # token: ${{secrets.GITHUB_TOKEN}}
