name: deployInternshalla
on:
  push:
    branches:
      - main
      - 'feat/**'
    paths-ignore:
      - '.github/workflows/*'
      - 'README.md'
  workflow_dispatch:
jobs:
  buildCode:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: print node
        run: | 
          echo "node is install successfully"
          node -v
      - name: create a cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{runner.os}}-build-${{hashFiles('**/package-lock.json')}}
      - name: Dependencies install
        run: |
          npm ci
          echo "dependencies install successfully"
      - name: Code deploy
        run: |
          npm run build
          echo "build successful"
      - name: Upload a artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-file
          path: dist
  deployCode:
    needs: buildCode
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-file
          path: dist
      - name: deploy successful
        run: echo "deploy successful"
